# docker-compose.test.yml 
#
# override file for test deployment
services:

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    ports:
      - "2998:8978"  # web ui
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    depends_on:
      - db

  db:
    volumes:
      - db-data-test:/var/lib/postgresql/data

  app:
    environment:
      - ENV=test # needed by docker-entrypoint.sh
    ports:
      - 2999:3000

volumes:
  cloudbeaver-data:
  db-data-test:

networks:
  default:
    name: hangman-net-test
