# docker-compose.test.yml 
#
# override file for test deployment
services:

  db:
    container_name: hangman-db-test
    volumes:
      - db-data-test:/var/lib/postgresql/data

  app:
    container_name: hangman-app-test
    environment:
      - ENV=test # needed by docker-entrypoint.sh
    ports:
      - 2999:3000
      - 5555:5555 # prisma studio

volumes:
  db-data-test:

networks:
  default:
    name: hangman-net-test
