# docker-compose.base.yml 
#
# partially configured services 
# deploy in both test and prod
services:

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - TZ=America/New_York

  app:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TZ=America/New_York
    depends_on:
      - db

# volumes + network defined in respective override file