services:

  postgres:
    image: postgres:17-alpine
    container_name: dev-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: supersecure
      POSTGRES_DB: devdb
      TZ: America/New_York
    ports:
      - "5432:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data

volumes:
  db-data-dev:
