name: Deploy App

on:
  push:
    branches:
      - main # prod
      - test
    # don't deploy on non code changes
    paths-ignore:
      - 'README.md'
      - '**/README.md'

jobs:
  deploy:
    runs-on: self-hosted

    # use correct github vars & secrets environemtns based on branch
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
    
    env:
      PROXY_NET: "nathan_default"
      IMAGE_NAME: "ghcr.io/nathanklein8/hangmanwebapp:${{ github.ref_name == 'main' && 'latest' || 'test' }}"

      # need to be set at build time
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build image
        run: |
          COMPOSE_BAKE=true docker compose \
            -f docker-compose.base.yml \
            build app

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Push Image to GHCR
        run: docker push ${IMAGE_NAME}

      - name: Start container
        run: |
          docker compose \
            -f docker-compose.base.yml \
            -f docker-compose.${ENV}.yml \
            up -d --remove-orphans

      - name: Connect App container to proxy network (prod only)
        if: env.ENV == 'prod'
        run: docker network connect ${PROXY_NET} hangman-app-prod

      - name: Cleanup unused images
        run: docker image prune -f
