name: Pull Image and deploy

on:
  workflow_run:
    workflows: ["Build Image and push to GHCR"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    # use correct github vars & secrets environemtns based on branch
    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || 'test' }}

    env:
      PROXY_NET: "nathan_default"
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

      # need to be set at build time
      ENV: ${{ github.ref_name == 'main' && 'prod' || 'test' }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}

    steps:
      - name: Deploy containers
        run: |
          docker compose \
            -f docker-compose.base.yml \
            -f docker-compose.${ENV}.yml \
            stop
          docker compose \
            -f docker-compose.base.yml \
            -f docker-compose.${ENV}.yml \
            rm --force
          docker compose \
            -f docker-compose.base.yml \
            -f docker-compose.${ENV}.yml \
            up -d --remove-orphans

      - name: Connect App container to proxy network (prod only)
        if: env.ENV == 'prod'
        run: docker network connect ${PROXY_NET} hangman-app-prod

      - name: Cleanup unused images
        run: docker image prune -f